# Generated by Django 6.0.3 on 2026-04-03 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000, unique=True, verbose_name='URL')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='page metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('save_count', models.IntegerField(default=0, editable=False, verbose_name='save count')),
                ('comment_count', models.IntegerField(default=0, editable=False, verbose_name='comment count')),
                ('last_saved_at', models.DateTimeField(blank=True, null=True, verbose_name='last saved at')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'db_table': 'link',
                'ordering': ('-last_saved_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tag',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='body')),
                ('body_html', models.TextField(blank=True, editable=False, verbose_name='body HTML')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='posted by')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to='core.link', verbose_name='link')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'comment',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('saved_your_link', 'saved your link'), ('commented_your_post', 'commented on your post')], max_length=32, verbose_name='type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('seen', models.BooleanField(default=False, verbose_name='seen')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', related_query_name='notification_sent', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', related_query_name='notification_received', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
                ('target_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', related_query_name='notification', to='core.comment', verbose_name='target comment')),
                ('target_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', related_query_name='notification', to='core.link', verbose_name='target link')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notification',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('content_html', models.TextField(blank=True, editable=False, verbose_name='content HTML')),
                ('is_listed', models.BooleanField(default=True, verbose_name='is listed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('contributors', models.ManyToManyField(blank=True, related_name='wiki_contributions', to=settings.AUTH_USER_MODEL, verbose_name='contributors')),
            ],
            options={
                'verbose_name': 'Wiki Page',
                'verbose_name_plural': 'Wiki Pages',
                'db_table': 'wiki_page',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=255, verbose_name='bio')),
                ('summary_mails', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('never', 'Never')], default='never', max_length=10, verbose_name='summary emails')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
                'db_table': 'user_preferences',
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('note_html', models.TextField(blank=True, editable=False, verbose_name='note HTML')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saves', related_query_name='save', to='core.bookmark', verbose_name='saved from')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', related_query_name='bookmark', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', related_query_name='bookmark', to='core.link', verbose_name='link')),
                ('tags', models.ManyToManyField(blank=True, related_name='bookmarks', to='core.tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmarks',
                'db_table': 'bookmark',
                'constraints': [models.UniqueConstraint(fields=('user', 'link'), name='uc_bookmark_user_link')],
            },
        ),
    ]
