# Generated by Django 6.0.3 on 2026-04-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='is_private',
            field=models.BooleanField(default=True, help_text='Only you can see this bookmark', verbose_name='private'),
        ),
    ]
