# Generated by Django 6.0.3 on 2026-04-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_bookmark_reading_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='pinned'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='pinned at'),
        ),
    ]
