# Generated by Django 6.0.3 on 2026-04-04 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_bookmark_pin_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='collection',
            name='uc_collection_user_slug',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='collections',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
